name: Build and Run

on:
  push:
    branches:
      - main  # ajuste o nome do branch conforme necessário
  pull_request:
    branches:
      - main  # ajuste o nome do branch conforme necessário

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.203' # ajuste para a versão do .NET que você está usando

    - name: Build
      run: dotnet build --configuration Release

    - name: Run
      run: dotnet run --project path/to/Aviator Predictor/Aviator-Hack.csproj
